image: samueldebruyn/debian-git

pipelines:
  custom:
     deployment-to-demo:
       - step:
          script:
            - apt-get update
            - ssh ubuntu@webshop.dev.gingerpayments.com mkdir /home/ubuntu/ems-hikashop
            - scp -r ./*   ubuntu@webshop.dev.gingerpayments.com:/home/ubuntu/ems-hikashop
            - ssh ubuntu@webshop.dev.gingerpayments.com sudo rm -rf /var/www/html/joomla/libraries/emspay/
            - ssh ubuntu@webshop.dev.gingerpayments.com sudo rm -rf /var/www/html/joomla/pkg_emspay
            - ssh ubuntu@webshop.dev.gingerpayments.com sudo rm -rf /var/www/html/joomla/ems-hikashop/plugins/hikashoppayment/emspay*
            - ssh ubuntu@webshop.dev.gingerpayments.com sudo cp -r /home/ubuntu/ems-hikashop/* /var/www/html/joomla/
            - ssh ubuntu@webshop.dev.gingerpayments.com sudo rm -rf /home/ubuntu/ems-hikashop
            - ssh ubuntu@webshop.dev.gingerpayments.com sudo cp /home/ubuntu/.env /var/www/html/joomla/libraries/emspay/ems-php/
            - ssh ubuntu@webshop.dev.gingerpayments.com sudo chown -R www-data:www-data /var/www/html/joomla/